#api_platform:
#    mapping:
#        paths: ['%kernel.project_dir%/src/Entity']

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    title:  API Platform Vuejs Symfony 4
    version: 1.0.0
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
