resources:
  App\Entity\Custom:
    collectionOperations:
      list_custom:
        route_name: 'list_custom'
        controller: 'App\Controller\CustomController'
        swagger_context:
          summary: get All custom
          responses:
            200:
              description: get All custom
              schema:
                type: object
                properties:
                  account_type:
                    type: string
                    description: type de compte

      pagination_custom:
        route_name: 'pagination_custom'
        controller: 'App\Controller\CustomController'
        swagger_context:
          parameters:
            - in: body
              name: body
              schema:
                type: object
                properties:
                  firstResult:
                    type: integer
                    description: firstResult
                  perPage:
                    type: integer
                    description: perPage
          summary: get All custom by pagination
          responses:
            200:
              description: get All custom by pagination
              schema:
                type: object
                properties:
                  account_type:
                    type: string
                    description: type de compte
    itemOperations:
      add_custom:
        route_name: 'add_custom'
        controller: 'App\Controller\CustomController'
        swagger_context:
          summary:  add custom
          parameters:
            - name: body
              in: body
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id of costum
                  title:
                    type: string
                    description: title
                  content:
                    type: string
                    description: title

          responses:
            200:
              description: custom add
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: result

      edit_custom:
        route_name: 'update_custom'
        controller: 'App\Controller\CustomController'
        swagger_context:
          summary:  edit custom
          parameters:
            - name: body
              in: body
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id of costum
                  title:
                    type: string
                    description: title
                  content:
                    type: string
                    description: title

          responses:
            200:
              description: custom add
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: result